DROP TABLE IF EXISTS xmo_user;

CREATE TABLE xmo_user
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    username VARCHAR(50) NULL DEFAULT NULL COMMENT '用户名',
    password VARCHAR(50) NULL DEFAULT NULL COMMENT '密码',
    salt VARCHAR(50) NULL DEFAULT NULL COMMENT '密码盐',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    nickname VARCHAR(30) NULL DEFAULT NULL COMMENT '昵称',
    age INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    disable CHAR(10) NULL DEFAULT NULL COMMENT '是否禁用',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS xmo_group;
CREATE TABLE xmo_group  (
  ID varchar(32) NOT NULL DEFAULT '' COMMENT '主键',
  GROUP_CODE varchar(30) NOT NULL DEFAULT '' COMMENT '用户组代码',
  GROUP_NAME varchar(100) NOT NULL DEFAULT '' COMMENT '用户组名称',
  DESCRIPTION varchar(200) NOT NULL DEFAULT '' COMMENT '用户组描述',
  ACTIVE char(1) NOT NULL DEFAULT '' COMMENT '激活',
  GROUP_TYPE varchar(11) NOT NULL DEFAULT '' COMMENT '用户组类型',
  PRIMARY KEY (ID),
  UNIQUE INDEX UNIQUE_GROUP_CODE(GROUP_CODE)
);

DROP TABLE IF EXISTS xmo_permission;

CREATE TABLE xmo_permission (
  ID varchar(32) NOT NULL DEFAULT '' COMMENT '主键',
  PERMISSION_NAME varchar(100) NOT NULL DEFAULT '' COMMENT '权限名称',
  PERMISSION_KEY varchar(100) NOT NULL DEFAULT '' COMMENT '权限KEY',
  PERMISSION_GROUP varchar(100) NOT NULL DEFAULT '' COMMENT '权限组',
  PERMISSION_URL varchar(100) NOT NULL DEFAULT '' COMMENT '权限URL',
  PERMISSION_ACTION varchar(100) NOT NULL DEFAULT '' COMMENT '权限ACTION',
  DESCRIPTION varchar(2000) NOT NULL DEFAULT '' COMMENT '权限描述',
  ACTIVE char(1) NOT NULL DEFAULT '' COMMENT '激活',
  CREATED_USER_ID varchar(32) NOT NULL DEFAULT '' COMMENT '创建人',
  CREATED_TIME datetime NOT NULL COMMENT '创建时间',
  UPDATED_USER_ID varchar(32) NOT NULL DEFAULT '' COMMENT '更新人',
  UPDATED_TIME datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (ID),
  UNIQUE KEY  PERMISSION_UN (PERMISSION_URL,PERMISSION_ACTION),
  UNIQUE KEY PERMISSION_KEY_UN (PERMISSION_KEY)
);

DROP TABLE IF EXISTS xmo_group_permission;
CREATE TABLE xmo_group_permission (
  ID varchar(32) NOT NULL DEFAULT '' COMMENT '主键',
  GROUP_ID varchar(32) NOT NULL DEFAULT '' COMMENT '组表ID',
  PERMISSION_ID varchar(32) NOT NULL DEFAULT '' COMMENT '权限表ID',
  PRIMARY KEY (ID),
  UNIQUE KEY GROUP_PERMISSION_UNIQUE (GROUP_ID,PERMISSION_ID)
);

DROP TABLE IF EXISTS xmo_user_group;
CREATE TABLE xmo_user_group (
  ID varchar(32) NOT NULL DEFAULT '' COMMENT '主键',
  GROUP_ID varchar(32) NOT NULL DEFAULT '' COMMENT '组表ID',
  USER_ID varchar(32) NOT NULL DEFAULT '' COMMENT '用户ID',
  PRIMARY KEY (ID),
  UNIQUE KEY USER_GROUP_UNIQUE (GROUP_ID,USER_ID)
);
